FROM python:3-alpine

COPY ./logtruncate /etc/periodic/daily/logtruncate
RUN chmod +x /etc/periodic/daily/logtruncate

COPY ./thermo.py .

RUN mkdir /var/log/thermo

CMD ["/bin/sh", "-c", "crond -b -l 8 && while true; do python thermo.py; sleep .25; done"]
